FROM centos

MAINTAINER githug_wj

RUN yum update -y \
    #&& dpkg-reconfigure -u \
    #&& apt-get install -y apt-utils \
    && yum install -y git \
    && yum install -y vim \
    && yum install -y ruby \
    && yum install -y rubygems \
    && gem install githug \
    && mkdir /git_hug \
    && cd /git_hug
    #&& sed -i 's/80/5000/' /etc/apache2/ports.conf

#ADD requirements.txt /tmp/requirements.txt
#RUN pip --default-timeout=100 install -r /tmp/requirements.txt

#RUN mkdir /var/www/public_html
#ADD flaskapp.wsgi /var/www/flaskapp/flaskapp.wsgi
#ADD flaskapp.cfg /etc/apache2/sites-available/flaskapp.conf
#RUN a2ensite flaskapp.conf

EXPOSE 8808

